"""
Operating-regime classifier and per-cluster causal scorer.

Loads cluster centroids and per-cluster LinearRegression coefficients from
data/processed/regime_coefficients.json (generated by
scripts/compute_regime_coefficients.py).

If the JSON file is absent (e.g. fresh Render deploy without raw data),
falls back to single-cluster mode using the FD001 global coefficients from
causal_scorer.FALLBACK_COEFFICIENTS — identical behaviour to the original
hardcoded "cluster_0".

Public API
----------
classify(op1, op2, op3) -> str
    Returns a cluster label such as "cluster_0" … "cluster_5".
    Uses nearest-centroid (Euclidean) assignment — fast, no sklearn needed
    at inference time.

compute_causal_score(reading, cluster_label) -> (float, dict)
    Scores one reading using the per-cluster causal coefficients.
    Returns (causal_score in [0,1], details dict of per-sensor residual z-scores).
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

import numpy as np

from backend.services.causal_scorer import FALLBACK_COEFFICIENTS

_COEFF_FILE = (
    Path(__file__).parent.parent.parent
    / "data" / "processed" / "regime_coefficients.json"
)

# Noise ceiling: causal_z / 5.0 → capped at 1.0
_NORM_CEILING = 5.0


# ---------------------------------------------------------------------------
# Load coefficients at module import
# ---------------------------------------------------------------------------

def _load() -> dict:
    if not _COEFF_FILE.exists():
        return {}
    try:
        with open(_COEFF_FILE) as f:
            return json.load(f)
    except Exception:
        return {}


_data = _load()

# Centroids as numpy array — shape (n_clusters, 3) or None in fallback mode
_centroids: Optional[np.ndarray] = (
    np.array(_data["centroids"]) if _data else None
)

# cluster_coefficients keyed by str(cluster_index)
_cluster_coefficients: dict[str, dict] = _data.get("cluster_coefficients", {})

# Single-cluster fallback built from FALLBACK_COEFFICIENTS
_FALLBACK_CLUSTER: dict[str, dict] = {
    sensor: {
        "cause": info["cause"],
        "coef": info["coef"],
        "intercept": info["intercept"],
        "residual_std": info["residual_std"],
    }
    for sensor, info in FALLBACK_COEFFICIENTS.items()
}


# ---------------------------------------------------------------------------
# Public functions
# ---------------------------------------------------------------------------

def classify(op1: float, op2: float, op3: float) -> str:
    """
    Assign a reading to its nearest operating-regime cluster.

    Returns "cluster_0" through "cluster_5" when regime_coefficients.json
    is loaded, or "cluster_0" in single-cluster (FD001) fallback mode.
    """
    if _centroids is None:
        return "cluster_0"

    point = np.array([[op1 or 0.0, op2 or 0.0, op3 or 0.0]])
    dists = np.linalg.norm(_centroids - point, axis=1)
    cluster_idx = int(np.argmin(dists))
    return f"cluster_{cluster_idx}"


def compute_causal_score(
    reading: dict,
    cluster_label: str,
) -> tuple[float, dict]:
    """
    Compute per-cluster causally-conditioned anomaly score for one reading.

    For each causal sensor:
        residual = observed − (coef × op_setting + intercept)
        causal_z = |residual| / residual_std

    Returns (causal_score in [0,1], {sensor: residual_z, ...}).
    Falls back to FALLBACK_COEFFICIENTS if the cluster has no data.
    """
    # Pick coefficient set for this cluster, or fallback
    cluster_idx = cluster_label.replace("cluster_", "")
    coef_set = _cluster_coefficients.get(cluster_idx, _FALLBACK_CLUSTER)

    causal_z_scores: list[float] = []
    details: dict[str, float] = {}

    for sensor, info in coef_set.items():
        sensor_val: Optional[float] = reading.get(sensor)
        cause_val: Optional[float] = reading.get(info["cause"])
        residual_std: float = info["residual_std"]

        if sensor_val is None or residual_std == 0:
            continue

        predicted = (
            info["coef"] * cause_val + info["intercept"]
            if cause_val is not None
            else info["intercept"]
        )
        residual_z = abs(sensor_val - predicted) / residual_std
        causal_z_scores.append(residual_z)
        details[sensor] = round(residual_z, 4)

    if not causal_z_scores:
        return 0.0, {}

    # Use top-k mean (k = min(3, n_sensors)) to mirror z-score's top-3-of-14
    # aggregation. Previously used mean of all 5, suppressing causal scores.
    k = min(3, len(causal_z_scores))
    top_k_mean = sum(sorted(causal_z_scores, reverse=True)[:k]) / k
    causal_score = min(top_k_mean / _NORM_CEILING, 1.0)
    return round(causal_score, 6), details


def get_alert_threshold(cluster_label: str) -> float:
    """
    Return the calibrated alert threshold for a given cluster.

    Looks up "alert_thresholds" in regime_coefficients.json, keyed by
    cluster index (e.g. "5" for cluster_5).  Falls back to 0.3 (the
    empirically-validated global default) if the key is absent.

    For FD002 (multi-cluster mode), thresholds were calibrated as the 90th
    percentile of early-life causal scores per dataset — see
    scripts/calibrate_thresholds.py.
    """
    thresholds = _data.get("alert_thresholds", {})
    key = cluster_label.replace("cluster_", "")
    return float(thresholds.get(key, 0.3))


# Expose whether we are in multi-cluster mode (useful for logging/testing)
is_multi_cluster: bool = _centroids is not None and len(_centroids) > 1
n_clusters: int = len(_centroids) if _centroids is not None else 1
